version: "3"

tasks:
  fmt:
    cmds:
      - tofu fmt -recursive terraform

  fmt:check:
    cmds:
      - tofu fmt -recursive -check terraform

  tflint:
    cmds:
      - tflint --init
      - tflint --chdir=terraform/envs/dev
      - tflint --chdir=terraform/modules/s3

  checkov:
    cmds:
      - checkov -d terraform -o json --soft-fail > .checkov.json
      - |-
        jq -r '
          ([.results.failed_checks[]? | select(.severity=="HIGH" or .severity=="CRITICAL")]) as $bad
          | "HIGH/CRITICAL findings: \($bad|length)"
        ' .checkov.json
      - |-
        jq -e '
          ([.results.failed_checks[]? | select(.severity=="HIGH" or .severity=="CRITICAL")] | length) == 0
        ' .checkov.json

  dev:planjson:
    dir: terraform/envs/dev
    cmds:
      - tofu init
      - tofu plan -out tfplan.binary
      - tofu show -json tfplan.binary > tfplan.json

  conftest:
    cmds:
      - conftest verify -p policies
      - conftest test terraform/envs/dev/tfplan.json -p policies --all-namespaces

  terratest:
    cmds:
      - go test -v ./tests/s3
